// This file was generated by executing this statement: wav2c healing_fixed.wav
extern uint16_t healing_fixed_wav[];
#define HEALING_FIXED_WAV_SAMPLE_RATE 480000
#define HEALING_FIXED_WAV_BITS_PER_SAMPLE 16
#define HEALING_FIXED_WAV_NUMBER_OF_SAMPLES 111167
