// This file was generated by executing this statement: wav2c healed.wav
extern uint16_t healed_wav[];
#define HEALED_WAV_SAMPLE_RATE 480000
#define HEALED_WAV_BITS_PER_SAMPLE 16
#define HEALED_WAV_NUMBER_OF_SAMPLES 140434
