// This file was generated by executing this statement: wav2c low_health.wav
extern uint16_t low_health_wav[];
#define LOW_HEALTH_WAV_SAMPLE_RATE 480000
#define LOW_HEALTH_WAV_BITS_PER_SAMPLE 16
#define LOW_HEALTH_WAV_NUMBER_OF_SAMPLES 74675
